# Generated by Django 2.1.4 on 2019-06-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraventanoagricola',
            name='precio',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='compraventanoagricola',
            name='tipo',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Baja', 'Baja')], default='0', max_length=15, null=True),
        ),
    ]
