# Generated by Django 2.1.4 on 2019-06-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_auto_20190612_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('direc', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Contacto',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='comprasporcinos',
            name='total_compra',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ganado',
            name='img',
            field=models.ImageField(upload_to='Ganado', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='ganado',
            name='img2',
            field=models.ImageField(upload_to='Ganado', verbose_name='Imagen2'),
        ),
        migrations.AlterField(
            model_name='ganado_sin_registro',
            name='img',
            field=models.ImageField(upload_to='Ganado', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='ganado_sin_registro',
            name='img2',
            field=models.ImageField(upload_to='Ganado', verbose_name='Imagen2'),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='tipo',
            field=models.CharField(choices=[('Sueldos', 'Sueldos'), ('Combustible', 'Combustible'), ('Insumo de alimentos', 'Insumo de alimentos'), ('Rentas', 'Rentas'), ('Derecho de agua', 'Derecho de agua'), ('Otros', 'Otros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecciongastos',
            name='tipo_gasto',
            field=models.CharField(choices=[('Sueldos', 'Sueldos'), ('Combustible', 'Combustible'), ('Insumo de alimentos', 'Insumo de alimentos'), ('Rentas', 'Rentas'), ('Derecho de agua', 'Derecho de agua'), ('Otros', 'Otros')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ventasporcinos',
            name='total_venta',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10),
        ),
    ]
